  - name: check weather the roboshot user exist or not
    ansible.builtin.command: id roboshop
    register: out #output is variable name
    ignore_errors: true

  - when: out.rc!= 0
    name: create a roboshop user
    become: yes
    ansible.builtin.user: 
      name: roboshop

  - name: check weather the /app directory exists or not 
    ansible.builtin.stat:
      path: /app
    register: directory

  - name: print the directory stats
    ansible.builtin.debug: 
      msg: "output: {{directory}}"

  - when: directory.stat.exists == false
    name: create /app directory
    ansible.builtin.file: 
      path: /app
      state: directory


  # here it is downloading from S3 AWS but i need to download it from nexus
  # - name: "downloading the {{component}} artifact"
  #   ansible.builtin.get_url:
  #     url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
  #     dest: /tmp

  # here it is downloading artifact from the nexus
  - name: "downloading the artifact from nexus"
    ansible.builtin.get_url:
      url: "{{nexus_url}}/{{component}}/{{group_id}}/{{component}}/{{app_version}}/{{component}}-{{app_version}}.zip"
      dest: "/app/{{component}}-{{app_version}}.zip"
      user_name: "{{nexus_username}}"
      password: "{{nexus_password}}"

  - name: unzipping the {{component}} files
    ansible.builtin.unarchive:
      src: "/app/{{component}}-{{app_version}}.zip"
      dest: "/app"
      remote_src: yes