  - name: maven package 
    ansible.builtin.command: mvn clean package
    args: 
      chdir: /app

  - name: rename jar file
    ansible.builtin.command: mv target/shipping-1.0.jar {{component}}.jar
    args: 
      chdir: /app